/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package di.uniba.map.b.uniperfida.frame;

import di.uniba.map.b.uniperfida.Engine;
import di.uniba.map.b.uniperfida.games.UniperfidaGame;
import di.uniba.map.b.uniperfida.parser.Parser;
import di.uniba.map.b.uniperfida.parser.ParserOutput;
import static di.uniba.map.b.uniperfida.print.Printings.*;
import di.uniba.map.b.uniperfida.type.AdvObject;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import static java.lang.System.out;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author antoniosilvestre
 */
public class EngineFrame extends javax.swing.JFrame {

    private UniperfidaGame game;
    private Parser parser;
    boolean noroom = false;
    boolean move = false;

    /**
     * Creates new form EngineFrame
     */
    public EngineFrame() {
        initComponents();
        init();
    }

    private void control() {
        if (noroom) { // se noroom = true
            GameTextArea.append("\nVerso questa direzione non puoi andare");
        } else if (move) { // se move = true
            if (game.getRooms().get(3).getCount() == 3) {
                //end1(out);
                GameTextArea.append("\nHai perso, 0 punti");
            }
            // out.println("*** " + getCurrentRoom().getName() + " ***"); // ti dice il nome della stanza
            GameTextArea.append("\n");
            GameTextArea.append("\n-----[" + game.getCurrentRoom().getuniverse() + "]-----\n");
            GameTextArea.append(game.getCurrentRoom().getDescription());
            GameTextArea.append("\n");
            if (!game.getCurrentRoom().getObjects().isEmpty()) {
                ObjectsTextArea.setText("");
                ObjectsTextArea.append("Sono presenti inoltre i seguenti oggetti:");
            } else {
                ObjectsTextArea.setText("");
                ObjectsTextArea.append("In questa stanza non ci sono oggetti.");
            }
            for (AdvObject o : game.getCurrentRoom().getObjects()) {
                ObjectsTextArea.append("\n- " + o.getName());
            }
            if (game.getRooms().get(25).getCount() == 4) {
                game.getRooms().get(25).setVisible(true);
            }
        }
        controlInventory();
    }

    private void controlButton() {
        if (game.getCurrentRoom() == game.getRooms().get(1) || game.getCurrentRoom() == game.getRooms().get(27) || game.getCurrentRoom() == game.getRooms().get(8) || game.getCurrentRoom() == game.getRooms().get(15)) {
            Push.setVisible(true);
        } else {
            Push.setVisible(false);
        }
        if (game.getCurrentRoom() == game.getRooms().get(2) || game.getCurrentRoom() == game.getRooms().get(3) || game.getCurrentRoom() == game.getRooms().get(7) || game.getCurrentRoom() == game.getRooms().get(10) || game.getCurrentRoom() == game.getRooms().get(26)) {
            Read.setVisible(true);
        } else {
            Read.setVisible(false);
        }
        if (game.getCurrentRoom() == game.getRooms().get(9) || game.getCurrentRoom() == game.getRooms().get(13)) {
            Up.setVisible(true);
            Down.setVisible(true);
        } else {
            Up.setVisible(false);
            Down.setVisible(false);
        }
        if (game.getCurrentRoom() == game.getRooms().get(24) || game.getCurrentRoom() == game.getRooms().get(12) || game.getCurrentRoom() == game.getRooms().get(2) || game.getCurrentRoom() == game.getRooms().get(4)) {
            PickUp.setVisible(true);
        } else {
            PickUp.setVisible(false);
        }
    }

    public void controlInventory() {
        int i = 0;
        if (!game.getInventory().isEmpty()) {
            for (AdvObject o : game.getInventory()) { // ciclo sugli elementi dell'inventario
                i++;
            }
            if (i == 1) {
                InventoryTextArea.setText("");
                InventoryTextArea.append("Nel tuo borsellino c'è una moneta");
            } else {
                InventoryTextArea.setText("");
                InventoryTextArea.append("Nel tuo borsellino ci sono " + i + " monete");
            }
        } else {
            InventoryTextArea.setText("");
            InventoryTextArea.append("Sei un poveraccio, non hai monete!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewGame = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        GameTextArea = new javax.swing.JTextArea();
        North = new javax.swing.JButton();
        South = new javax.swing.JButton();
        East = new javax.swing.JButton();
        West = new javax.swing.JButton();
        Push = new javax.swing.JButton();
        PickUp = new javax.swing.JButton();
        Open = new javax.swing.JButton();
        Talk = new javax.swing.JButton();
        Use = new javax.swing.JButton();
        Up = new javax.swing.JButton();
        Down = new javax.swing.JButton();
        Read = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObjectsTextArea = new javax.swing.JTextArea();
        ProfessorsName = new javax.swing.JTextField();
        Insert = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        InventoryTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NewGame.setText("Nuova Partita");
        NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameActionPerformed(evt);
            }
        });

        GameTextArea.setColumns(20);
        GameTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        GameTextArea.setRows(5);
        jScrollPane2.setViewportView(GameTextArea);

        North.setText("N");
        North.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NorthActionPerformed(evt);
            }
        });

        South.setText("S");
        South.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SouthActionPerformed(evt);
            }
        });

        East.setText("E");
        East.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EastActionPerformed(evt);
            }
        });

        West.setText("O");
        West.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WestActionPerformed(evt);
            }
        });

        Push.setText("Premi");
        Push.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PushActionPerformed(evt);
            }
        });

        PickUp.setText("Prendi");
        PickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickUpActionPerformed(evt);
            }
        });

        Open.setText("Apri");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        Talk.setText("Parla");

        Use.setText("Usa");
        Use.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseActionPerformed(evt);
            }
        });

        Up.setText("Sali");
        Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpActionPerformed(evt);
            }
        });

        Down.setText("Scendi");
        Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownActionPerformed(evt);
            }
        });

        Read.setText("Leggi");
        Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadActionPerformed(evt);
            }
        });

        ObjectsTextArea.setColumns(20);
        ObjectsTextArea.setRows(5);
        jScrollPane1.setViewportView(ObjectsTextArea);

        Insert.setText("Inserisci");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        InventoryTextArea.setColumns(20);
        InventoryTextArea.setRows(5);
        jScrollPane3.setViewportView(InventoryTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Use, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Talk, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Push, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Read)))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Up, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Down, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PickUp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(West, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(North, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(South, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(East, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProfessorsName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Insert)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Talk)
                            .addComponent(Push))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Use)
                            .addComponent(Read)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Up)
                            .addComponent(PickUp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Down)
                            .addComponent(Open))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(North)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(South))
                            .addComponent(West, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(East, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProfessorsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Insert))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameActionPerformed
        // TODO add your handling code here:
        GameTextArea.setText("");
        GameTextArea.append("\n\nUniverso T-237, Terra, laboratorio di ricerca “Pablo Escobar”, Martedì, 4 Maggio 2021."
                + "\nIl professor Silvestre ha finalmente ultimato il suo progetto: una macchina che permette di viaggiare tra gli universi."
                + "\n“Assistente Olivieri, venga qui e mi dica cosa vede.” "
                + "\n“Vedo una macchina interdimensionale?” "
                + "\n“No, è la nostra possibilità per sbagliare, il nostro mondo è talmente perfetto che non ci permette di capire cosa sia giusto o sbagliato”"
                + "\n“Non capisco”"
                + "\n“C’è un universo, conosciuto come J-371, in cui ci sono le stesse persone."
                + "\nPensa: la loro libertà, senza alcun vincolo morale, ha reso quel mondo invivibile. Viviamo due situazioni diametralmente opposte ma desideriamo la stessa cosa: evadere."
                + "\nOra ci serve solo una cavia."
                + "\nSecondo la legge dei Multiversi, se una persona effettua un viaggio interdimensionale si ritroverà nello stesso nostro anno, a vivere una vita che è sua solo in quell’universo,"
                + "\nquindi io lì potrei essere un delinquente!”"
                + "\n“Ce l’ho, ce l’ho, conosco un tipo di nome Edoardo abbastanza sconsiderato da affrontare un viaggio da cui potrebbe non fare ritorno” "
                + "\n“Okay, ci incontriamo qui giovedì alle 15”.");
        GameTextArea.append("\n");
        GameTextArea.append("\n...\n");
        GameTextArea.append("...\n");
        GameTextArea.append("\n**********DUE GIORNI DOPO**********");
        GameTextArea.append("\n\n“Buongiorno professor Silvestre, io sono Edoardo.”"
                + "\n“Ciao Edoardo. Sono molto felice di conoscerti, prima di partire lascia che ti spieghi un paio di cose. Iniziamo subito, sei pronto?”"
                + "\n“Sissignore!”"
                + "\n“Come vedi questa è una macchina interdimensionale e serve per viaggiare attraverso i Multiversi."
                + "\nIl viaggio durerà qualche secondo e non ti accorgerai di nulla. Una volta dentro la macchina, premi il tasto rosso per partire. "
                + "\nRicorda: hai a disposizione solamente sessanta minuti. Passata l’ora ritorna esattamente nel punto in cui hai approdato”"
                + "\n“Ho capito, ci sono rischi?”"
                + "\n“No”."
                + "\n..."
                + "\n..."
                + "\n“Ah dimenticavo, molto probabilmente ti ritroverai in un mondo diviso per nazioni e lingue. Ancora non conoscono bene il concetto di integrazione, in bocca al lupo!”.");
        GameTextArea.append("\n-----[" + game.getCurrentRoom().getuniverse() + "]-----\n");
        GameTextArea.append(game.getCurrentRoom().getDescription());
        NewGame.setVisible(false);
        North.setVisible(true);
        South.setVisible(true);
        East.setVisible(true);
        West.setVisible(true);
        Open.setVisible(true);
        PickUp.setVisible(true);
        Talk.setVisible(true);
        Use.setVisible(true);
    }//GEN-LAST:event_NewGameActionPerformed

    private void EastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EastActionPerformed
        // TODO add your handling code here:
        if (game.getCurrentRoom().getEast() != null) {
            game.setCurrentRoom(game.getCurrentRoom().getEast());
            move = true;
            noroom = false;
        } else {
            noroom = true;
            move = false;
        }
        control();
        controlButton();
    }//GEN-LAST:event_EastActionPerformed

    private void NorthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NorthActionPerformed
        // TODO add your handling code here:
        if (game.getCurrentRoom().getNorth() != null && game.getCurrentRoom() != game.getRooms().get(27)) {
            game.setCurrentRoom(game.getCurrentRoom().getNorth());
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(27) && !game.getRooms().get(27).isPrint()) {
            game.setCurrentRoom(game.getCurrentRoom().getNorth());
            move = true;
            noroom = false;
            GameTextArea.append("\nAll'improvviso, a causa del vento, ti capita tra le mani un fogliettino che recita:"
                    + "\nMessaggio per l'Edoardo Pomarico del futuro: aiutami a verbalizzare il voto, non riesco a prenotare il ricevimento con il prof. Basilico perchè l'app MyUni fa schifo!"
                    + "\nChe coincidenza! Nel tuo primo passo sul nuovo universo hai scoperto due cose: il tuo obiettivo e il fatto che il tuo alter ego sia uno svitato!");
            game.getRooms().get(27).setPrint(true);
        } else if (game.getCurrentRoom() == game.getRooms().get(27) && game.getRooms().get(27).isPrint()) {
            game.setCurrentRoom(game.getCurrentRoom().getNorth());
            move = true;
            noroom = false;
        } else {
            noroom = true;
            move = false;
        }
        control();
        controlButton();
    }//GEN-LAST:event_NorthActionPerformed

    private void SouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SouthActionPerformed
        // TODO add your handling code here:
        if (game.getCurrentRoom().getSouth() != null) {
            game.setCurrentRoom(game.getCurrentRoom().getSouth());
            move = true;
            noroom = false;
        } else {
            noroom = true;
            move = false;
        }
        control();
        controlButton();
    }//GEN-LAST:event_SouthActionPerformed

    private void WestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WestActionPerformed
        // TODO add your handling code here:
        if (game.getCurrentRoom().getWest() != null && game.getCurrentRoom() != game.getRooms().get(23) && game.getCurrentRoom() != game.getRooms().get(25)) {
            game.setCurrentRoom(game.getCurrentRoom().getWest());
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(23) && game.getRooms().get(25).isVisible()) {
            game.setCurrentRoom(game.getCurrentRoom().getWest());
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(23) && !game.getRooms().get(25).isVisible()) {
            GameTextArea.append("\nPer entrare dal prof. Basilico devi prima risolvere gli indovinelli.");
            GameTextArea.append("\n");
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(25) && !game.getRooms().get(28).isVisible()) {
            GameTextArea.append("\nDevi aprire la porta per entrare!");
            GameTextArea.append("\n");
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(25) && game.getRooms().get(28).isVisible()) {
            game.setCurrentRoom(game.getCurrentRoom().getWest());
            move = true;
            noroom = false;
        } else {
            noroom = true;
            move = false;
        }
        control();
        controlButton();
    }//GEN-LAST:event_WestActionPerformed

    private void PushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PushActionPerformed
        // TODO add your handling code here:
        if (game.getCurrentRoom() == game.getRooms().get(1)) {
            game.setCurrentRoom(game.getRooms().get(27));
            move = true;
            noroom = false;
            // out.println("*** " + getCurrentRoom().getName() + " ***"); // ti dice il nome della stanza
            GameTextArea.append("\nFatto! Hai premuto il bottone\n");
            GameTextArea.append("\n");
            GameTextArea.append("...");
            GameTextArea.append("\nSei in viaggio verso il nuovo universo\n");
            GameTextArea.append("...");
        } else if (game.getCurrentRoom() == game.getRooms().get(27)) {

            game.setCurrentRoom(game.getRooms().get(1));
            move = true;
            noroom = false;
            // out.println("*** " + getCurrentRoom().getName() + " ***"); // ti dice il nome della stanza
            GameTextArea.append("\nFatto! Hai premuto il bottone\n");
            GameTextArea.append("\n");
            GameTextArea.append("...");
            GameTextArea.append("\nSei in viaggio verso il tuo universo\n");
            GameTextArea.append("...");
        } else if (game.getCurrentRoom() == game.getRooms().get(8) || game.getCurrentRoom() == game.getRooms().get(15)) {
            GameTextArea.append("\nL'ascensore non è disponibile.");
            GameTextArea.append("\n");
            move = true;
            noroom = false;
        }
        control();
    }//GEN-LAST:event_PushActionPerformed

    private void UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpActionPerformed
        // TODO add your handling code here:
        if (game.getCurrentRoom().getUp() != null) { // controlla se su si può andare
            game.setCurrentRoom(game.getCurrentRoom().getUp()); // se su si può andare setto la nuova stanza corrente
            move = true;
            noroom = false;
        } else {
            noroom = true;
            move = false;
        }
        control();
        controlButton();
    }//GEN-LAST:event_UpActionPerformed

    private void DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownActionPerformed
        // TODO add your handling code here:
        if (game.getCurrentRoom().getDown() != null && game.getCurrentRoom() != game.getRooms().get(11)) { // controlla se su si può andare
            game.setCurrentRoom(game.getCurrentRoom().getDown()); // se su si può andare setto la nuova stanza corrente
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(11) && game.getRooms().get(26).isVisible()) {
            game.setCurrentRoom(game.getCurrentRoom().getDown()); // se su si può andare setto la nuova stanza corrente
            move = true;
            noroom = false;
        } else {
            noroom = true;
            move = true;
        }
        control();
        controlButton();
    }//GEN-LAST:event_DownActionPerformed

    private void ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadActionPerformed
        // TODO add your handling code here:
        if (game.getCurrentRoom() == game.getRooms().get(2)) { //cartello in cortile
            GameTextArea.append("\nIl cartello recita:\n" + game.getCurrentRoom().getObjects().get(1).getDescription());
            GameTextArea.append("\n");
            move = true;
            noroom = false;
            game.getRooms().get(2).getObjects().get(1).setDescription("'Università di Bari Aldo Moro, Facoltà di Informatica'.");
        } else if (game.getCurrentRoom() == game.getRooms().get(3)) { //bacheca in hall
            GameTextArea.append("\nNella bacheca c'è scritto:\n" + game.getCurrentRoom().getObjects().get(0).getDescription());
            GameTextArea.append("\n");
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(7)) {
            GameTextArea.append("\nNella bacheca c'è scritto:\n" + game.getCurrentRoom().getObjects().get(0).getDescription());
            GameTextArea.append("\n");
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(10)) {
            GameTextArea.append("\nNella bacheca c'è scritto:\n" + game.getCurrentRoom().getObjects().get(0).getDescription());
            GameTextArea.append("\n");
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(26)) {
            GameTextArea.append("\nIl foglio recita:\n" + game.getCurrentRoom().getObjects().get(0).getDescription());
            GameTextArea.append("\n");
            move = true;
            noroom = false;
        }
    }//GEN-LAST:event_ReadActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
        int j = game.getRooms().get(25).getCount();
        if (game.getCurrentRoom() == game.getRooms().get(18)) {
            String rossetto = ProfessorsName.getText();
            switch (rossetto) {
                case "rossetto":
                    GameTextArea.append("\nSoluzione corretta, autenticazione #1 riuscita.\n");
                    game.getCurrentRoom().getObjects().get(0).setUsed(true);
                    Insert.setVisible(false);
                    ProfessorsName.setVisible(false);
                    move = true;
                    noroom = false;
                    game.getRooms().get(25).setCount(++j);
                    break;
                case "0":
                    GameTextArea.append("Autenticazione #1 fallita.");
                    move = true;
                    noroom = false;
                    break;
                default:
                    GameTextArea.append("Il nome non è corretto. \nInserisci di nuovo il nome:");
                    break;
            }
        } else if (game.getCurrentRoom() == game.getRooms().get(19)) {
            String impavido = ProfessorsName.getText();
            switch (impavido) {
                case "impavido":
                    GameTextArea.append("\nSoluzione corretta, autenticazione #2 riuscita.\n");
                    game.getCurrentRoom().getObjects().get(0).setUsed(true);
                    Insert.setVisible(false);
                    ProfessorsName.setVisible(false);
                    move = true;
                    noroom = false;
                    game.getRooms().get(25).setCount(++j);
                    break;
                case "0":
                    GameTextArea.append("Autenticazione #2 fallita.");
                    move = true;
                    noroom = false;
                    break;
                default:
                    GameTextArea.append("Il nome non è corretto. \nInserisci di nuovo il nome:");
                    break;
            }
        } else if (game.getCurrentRoom() == game.getRooms().get(21)) {
            String gatto = ProfessorsName.getText();
            switch (gatto) {
                case "gatto":
                    GameTextArea.append("\nSoluzione corretta, autenticazione #3 riuscita.\n");
                    game.getCurrentRoom().getObjects().get(0).setUsed(true);
                    Insert.setVisible(false);
                    ProfessorsName.setVisible(false);
                    move = true;
                    noroom = false;
                    game.getRooms().get(25).setCount(++j);
                    break;
                case "0":
                    GameTextArea.append("Autenticazione #3 fallita.");
                    move = true;
                    noroom = false;
                    break;
                default:
                    GameTextArea.append("Il nome non è corretto. \nInserisci di nuovo il nome:");
                    break;
            }
        } else if (game.getCurrentRoom() == game.getRooms().get(22)) {
            String cinquanta = ProfessorsName.getText();
            switch (cinquanta) {
                case "cinquanta":
                    GameTextArea.append("\nSoluzione corretta, autenticazione #4 riuscita.\n");
                    game.getCurrentRoom().getObjects().get(0).setUsed(true);
                    Insert.setVisible(false);
                    ProfessorsName.setVisible(false);
                    move = true;
                    noroom = false;
                    game.getRooms().get(25).setCount(++j);
                    break;
                case "0":
                    GameTextArea.append("Autenticazione #4 fallita.");
                    move = true;
                    noroom = false;
                    break;
                default:
                    GameTextArea.append("Il nome non è corretto. \nInserisci di nuovo il nome:");
                    break;
            }
        }
        control();
        controlButton();
    }//GEN-LAST:event_InsertActionPerformed

    private void UseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseActionPerformed
        // TODO add your handling code here:
        if (game.getCurrentRoom() == game.getRooms().get(18)) {
            if (!game.getCurrentRoom().getObjects().get(0).isUsed()) {
                GameTextArea.append("\nMenu Rossetto\n");
                Insert.setVisible(true);
                ProfessorsName.setVisible(true);
                move = false;
                noroom = false;
            } else {
                GameTextArea.append("Qui ti sei già autenticato!");
                GameTextArea.append("\n");
                move = true;
                noroom = false;
            }
        } else if (game.getCurrentRoom() == game.getRooms().get(19)) {
            if (!game.getCurrentRoom().getObjects().get(0).isUsed()) {
                GameTextArea.append("\nMenu Impavido\n");
                Insert.setVisible(true);
                ProfessorsName.setVisible(true);
                move = false;
                noroom = false;
            } else {
                GameTextArea.append("Qui ti sei già autenticato!");
                GameTextArea.append("\n");
                move = true;
                noroom = false;
            }
        } else if (game.getCurrentRoom() == game.getRooms().get(21)) {
            if (!game.getCurrentRoom().getObjects().get(0).isUsed()) {
                GameTextArea.append("\nMenu Gatto\n");
                Insert.setVisible(true);
                ProfessorsName.setVisible(true);
                move = false;
                noroom = false;
            } else {
                GameTextArea.append("Qui ti sei già autenticato!");
                GameTextArea.append("\n");
                move = true;
                noroom = false;
            }
        } else if (game.getCurrentRoom() == game.getRooms().get(22)) {
            if (!game.getCurrentRoom().getObjects().get(0).isUsed()) {
                GameTextArea.append("\nMenu Cinquanta\n");
                Insert.setVisible(true);
                ProfessorsName.setVisible(true);
                move = false;
                noroom = false;
            } else {
                GameTextArea.append("Qui ti sei già autenticato!");
                GameTextArea.append("\n");
                move = true;
                noroom = false;
            }
        }
        control();
        controlButton();
    }//GEN-LAST:event_UseActionPerformed

    private void PickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickUpActionPerformed
        // TODO add your handling code here:
        int i = 0;
        if (game.getCurrentRoom() == game.getRooms().get(24)) { //cartello in cortile
            GameTextArea.append("\nFatto, hai preso la moneta!");
            GameTextArea.append("\n");
            game.getCurrentRoom().getObjects().get(0).setPickupable(false);
            game.getCurrentRoom().getObjects().get(0).setDroppable(true);
            game.getInventory().add(game.getCurrentRoom().getObjects().get(0));
            game.getCurrentRoom().getObjects().remove(0);
            controlInventory();
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(12)) { //bacheca in hall
            GameTextArea.append("\nFatto, hai preso la moneta!");
            GameTextArea.append("\n");
            game.getCurrentRoom().getObjects().get(0).setPickupable(false);
            game.getCurrentRoom().getObjects().get(0).setDroppable(true);
            game.getInventory().add(game.getCurrentRoom().getObjects().get(0));
            game.getCurrentRoom().getObjects().remove(0);
            controlInventory();
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(2)) {
            GameTextArea.append("\nFatto, hai preso la moneta!");
            GameTextArea.append("\n");
            game.getCurrentRoom().getObjects().get(0).setPickupable(false);
            game.getCurrentRoom().getObjects().get(0).setDroppable(true);
            game.getInventory().add(game.getCurrentRoom().getObjects().get(0));
            game.getCurrentRoom().getObjects().remove(0);
            controlInventory();
            move = true;
            noroom = false;
        } else if (game.getCurrentRoom() == game.getRooms().get(4)) {
            GameTextArea.append("\nNon si ruba!");
            GameTextArea.append("\n");
            move = true;
            noroom = false;
        }
    }//GEN-LAST:event_PickUpActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenActionPerformed

    /**
     * @param args the command line arguments
     */
    private void init() {
        game = new UniperfidaGame();
        try {
            this.game.init();
            this.game.useFileRoomsDescription();
            this.game.useFileRoomsLook();
            this.game.useFileRoomsName();
            North.setVisible(false);
            South.setVisible(false);
            East.setVisible(false);
            West.setVisible(false);
            Push.setVisible(false);
            Open.setVisible(false);
            PickUp.setVisible(false);
            Talk.setVisible(false);
            Up.setVisible(false);
            Use.setVisible(false);
            Down.setVisible(false);
            Read.setVisible(false);
            Insert.setVisible(false);
            ProfessorsName.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
        GameTextArea.setText("");
        GameTextArea.append("\n"
                + "\n==================================="
                + "\n * Uniperfida v. 1.1 - 2020-2021 *"
                + "\n==================================="
                + "\nBENVENUTO");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EngineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EngineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EngineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EngineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EngineFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Down;
    private javax.swing.JButton East;
    private javax.swing.JTextArea GameTextArea;
    private javax.swing.JButton Insert;
    private javax.swing.JTextArea InventoryTextArea;
    private javax.swing.JButton NewGame;
    private javax.swing.JButton North;
    private javax.swing.JTextArea ObjectsTextArea;
    private javax.swing.JButton Open;
    private javax.swing.JButton PickUp;
    private javax.swing.JTextField ProfessorsName;
    private javax.swing.JButton Push;
    private javax.swing.JButton Read;
    private javax.swing.JButton South;
    private javax.swing.JButton Talk;
    private javax.swing.JButton Up;
    private javax.swing.JButton Use;
    private javax.swing.JButton West;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
